### ISSUE TITLE
Increase retryCount?

### ISSUE THREAD

**Issue by patrykkopycinski** [OpusCapitaBusinessNetwork/db-init#2]
In local dev it seems sometimes 5s is too short to start a mysql. As a workaround i did set retryCount to 50 and it helped, but doing that in all projects is overkill. Maybe we could increase default value to 30?

**Comment by kwierchris** [comment]
This value is already pretty high. I don't think we should increase this default value just because of the development system as this retry could lead to problems when our system runs in production mode later.
